#!/usr/bin/env bash
# This script displays "to infinity and beyond" indefinitely
#Requirement: in between each iteration of the loop, add a sleep 2

while true
do
	echo "To infinity and beyond"
	sleep 2
done
