#!/usr/bin/env bash
# this script displays "to infinity and beyond" indefinitely
#Requiremenmt: in iteration of the loop add sleep 2 inbetween of each

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
