#!/usr/bin/env bash
#this script displays the contents of the file '/etc/passwd'
#only display the username, user id and the user home directory path

myfile="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
