#!/usr/bin/env bash
# Write a bash script that displays number from 1 to 20 and:
# displays 4 and the bad luck from china for the 4th iteration
# displays 9 and the bad luck from japan for the 9th iteration
# displays 17 and the bad luck from italy for the 17th loop iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	(( i++ ))
done
